"""empty message

Revision ID: 3aaf7d4115dd
Revises: 97fee3111d57
Create Date: 2023-10-13 12:39:48.603477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaf7d4115dd'
down_revision: Union[str, None] = '97fee3111d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('inn', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'inn')
    # ### end Alembic commands ###
