"""person add phone

Revision ID: 97fee3111d57
Revises: 39a80a8af15f
Create Date: 2023-10-13 12:37:38.396380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fee3111d57'
down_revision: Union[str, None] = '39a80a8af15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'phone')
    # ### end Alembic commands ###
